room_list = [
  ["Endpoint", true, "Shit", "Shit.", 9 ],
  ["Dummy", nil, nil, nil, nil],
  ["Dummy", nil, nil, nil, nil],
  ['Backway entrance', true, "This can’t be, the workshop is empty? Damn.  Hmm that chunk of wall looks suspect.”,  'If I had some explosives I could blow up the wall...", 7 ],
  ["Dummy", nil, nil, nil, nil],
  ["Dummy", nil, nil, nil, nil],
  ["Back way",  true, "At least there is not a laser field fence of death blocking my way...", 'I am going to need to find a sentry component to unlock this door', 9],
  ["Dummy", nil, nil, nil, nil],
  ["Dummy", nil, nil, nil, nil],
  ["Cargo Yard", true, "There is a sentry detected. Exercise caution.", "The sentry might have a gun, but they don’t have sensors on the back of their heads… yet.", 10],
  ["Facility Entrace", true, "Just the place I need to get to! With a convenient laser fence in the way...", " Things I can do about the laser fence: 0",9 ],
  ["Rundown Shack Inside", true, " Hopefully I can find something useful in this rundown shack.", "This whole town is in ruin… but where are the people?",8 ],
  [" South West Ruins", true, 'When I left this place, there was people and androids everywhere, what happened?", "That switch might activate the doors in the southeast ruins.' ,12 ],
  ["Streets", true, "What a disaster, I hope Hector is holed up in his workshop.", 'I have only been gone for three years… What the hell happened?', 9 ],
  ["South East Ruins", true, "Hmm that shack looks like it has not been opened in years, maybe something useful is in there.", "Perhaps there is a console elsewhere that will open that door..",8 ],
]

room_list.each do | name, first_time, first_description, normal_description, row_max|
  Room.create( name: name, first_time: first_time, first_description: first_description, normal_description: normal_description, row_max: row_max)
end

tile_list1 = [
["facility_wall", 1, 9, true, nil],
["facility_wall_single", 1, 9, true, nil],
["facility_wall_single", 1, 9, true, nil],
["building_roof_topl", 1, 9, true, nil],
["building_roof_topc", 1, 9, true, nil],
["building_roof_topc", 1, 9, true, nil],
["building_roof_topc", 1, 9, true, nil],
["building_roof_topr", 1, 9, true, nil],
["facility_wall", 1, 9, true, nil],

["facility_wall", 1, 9, true, nil],
["facility_ground2", 1, 9, false, nil],
["facility_ground2", 1, 9, false, nil],
["building_roof_botl", 1, 9, true, nil],
["building_roof_botc", 1, 9, true, nil],
["building_roof_botc", 1, 9, true, nil],
["building_roof_botc", 1, 9, true, nil],
["building_roof_botr", 1, 9, true, nil],
["facility_wall", 1, 9, true, nil],

["facility_wall", 1, 9, true, nil],
["facility_ground2", 1, 9, false, nil],
["facility_ground1", 1, 9, false, nil],
["facility_wall_single", 1, 9, true, nil],
["facility_doorl_single", 1, 9, true, nil],
["facility_doorr_single", 1, 9, true, nil],
["facility_wall_single", 1, 9, true, nil],
["facility_wall_single", 1, 9, true, nil],
["facility_wall", 1, 9, true, nil],

["facility_wall", 1, 9, true, nil],
["facility_ground3", 1, 9, false, nil],
["facility_ground4", 1, 9, false, nil],
["facility_ground1", 1, 9, false, nil],
["facility_ground2", 1, 9, false, nil],
["facility_ground3", 1, 9, false, nil],
["facility_ground4", 1, 9, false, nil],
["facility_ground1", 1, 9, false, nil],
["facility_wall", 1, 9, true, nil],

["facility_wall", 1, 9, true, nil],
["facility_ground3", 1, 9, false, nil],
["facility_ground4", 1, 9, false, nil],
["facility_ground1", 1, 9, false, nil],
["facility_ground2", 1, 9, false, nil],
["facility_ground3", 1, 9, false, nil],
["facility_ground4", 1, 9, false, nil],
["facility_ground1", 1, 9, false, nil],
["facility_wall", 1, 9, true, nil],

["facility_wall", 1, 9, true, nil],
["facility_ground3", 1, 9, false, nil],
["facility_ground4", 1, 9, false, nil],
["facility_ground1", 1, 9, false, nil],
["facility_ground2", 1, 9, false, nil],
["facility_ground3", 1, 9, false, nil],
["facility_ground4", 1, 9, false, nil],
["facility_ground1", 1, 9, false, nil],
["facility_wall", 1, 9, true, nil],

["facility_wall", 1, 9, true, nil],
["facility_ground3", 1, 9, false, nil],
["facility_ground4", 1, 9, false, nil],
["facility_ground1", 1, 9, false, 1],
["facility_ground2", 1, 9, false, 1],
["facility_ground3", 1, 9, false, nil],
["facility_ground4", 1, 9, false, nil],
["facility_ground1", 1, 9, false, nil],
["facility_wall", 1, 9, true, nil],

["blank", 1, 9, true, nil],
["blank", 1, 9, true, nil],
["blank", 1, 9, true, nil],
["blank", 1, 9, true, nil],
["blank", 1, 9, true, nil],
["blank", 1, 9, true, nil],
["blank", 1, 9, true, nil],
["blank", 1, 9, true, nil],
["blank", 1, 9, true, nil]
]
tile_list1.each do | tile_name, room_id, row_max, is_solid, transition_tile|
  Tile.create( tile_name: tile_name, room_id: room_id, row_max: row_max, is_solid: is_solid, transition_tile: transition_tile)
end

tile_list2 = [
["blank", 2, 8, true, nil],
["facility_insidewall", 2, 8, true, nil],
["facility_insidewall", 2, 8, true, nil],
["facility_insidewall", 2, 8, true, nil],
["facility_insidewall", 2, 8, true, nil],
["facility_insidewall", 2, 8, true, nil],
["facility_insidewall", 2, 8, true, nil],
["blank", 2, 8, true, nil],

["blank", 2, 8, true, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["blank", 2, 8, true, nil],

["blank", 2, 8, true, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["blank", 2, 8, true, nil],

["blank", 2, 8, true, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["blank", 2, 8, true, nil],

["facility_outsidewall", 2, 8, true, nil],
["facility_outsidewall", 2, 8, true, nil],
["facility_insideground", 2, 8, false, nil],
["facility_insideground", 2, 8, false, nil],
["facility_outsidewall", 2, 8, true, nil],
["facility_outsidewall", 2, 8, true, nil],
["facility_outsidewall", 2, 8, true, nil],
["facility_outsidewall", 2, 8, true, nil],

["blank", 2, 8, true, nil],
["blank", 2, 8, true, nil],
["blank", 2, 8, true, nil],
["blank", 2, 8, true, nil],
["blank", 2, 8, true, nil],
["blank", 2, 8, true, nil],
["blank", 2, 8, true, nil],
["blank", 2, 8, true, nil]

  ]
tile_list2.each do | tile_name, room_id, row_max, is_solid, transition_tile|
  Tile.create( tile_name: tile_name, room_id: room_id, row_max: row_max, is_solid: is_solid, transition_tile: transition_tile)
end

tile_list3 = [
["blank", 3, 9, true, nil],
["facility_insidewall", 3, 9, true, nil],
["facility_insidewall", 3, 9, true, nil],
["facility_insidewall", 3, 9, true, nil],
["facility_insidewall", 3, 9, true, nil],
["facility_insidewall", 3, 9, true, nil],
["facility_insidewall", 3, 9, true, nil],
["facility_insidewall", 3, 9, true, nil],
["blank", 3, 9, true, nil],

["blank", 3, 9, true, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["blank", 3, 9, true, nil],

["blank", 3, 9, true, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["blank", 3, 9, true, nil],

["blank", 3, 9, true, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["blank", 3, 9, true, nil],

["blank", 3, 9, true, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["blank", 3, 9, true, nil],

["blank", 3, 9, true, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["blank", 3, 9, true, nil],

["facility_outsidewall", 3, 9, true, nil],
["facility_outsidewall", 3, 9, true, nil],
["facility_insideground", 3, 9, false, nil],
["facility_insideground", 3, 9, false, nil],
["facility_outsidewall", 3, 9, true, nil],
["facility_outsidewall", 3, 9, true, nil],
["facility_outsidewall", 3, 9, true, nil],
["facility_outsidewall", 3, 9, true, nil],

["blank", 3, 9, true, nil],
["blank", 3, 9, true, nil],
["blank", 3, 9, true, nil],
["blank", 3, 9, true, nil],
["blank", 3, 9, true, nil],
["blank", 3, 9, true, nil],
["blank", 3, 9, true, nil],
["blank", 3, 9, true, nil],
["blank", 3, 9, true, nil]
  ]
tile_list3.each do | tile_name, room_id, row_max, is_solid, transition_tile|
  Tile.create( tile_name: tile_name, room_id: room_id, row_max: row_max, is_solid: is_solid, transition_tile: transition_tile)
end

tile_list4 = [

["facility_wall_gap", 4, 9, true, nil],
["facility_wall_top", 4, 9, true, nil],
["facility_wall_gap", 4, 9, true, nil],
["facility_wall_top", 4, 9, true, nil],
["facility_ground4", 4, 9, false, nil],
["facility_ground3", 4, 9, false, nil],
["facility_wall_top", 4, 9, true, nil],
["facility_wall_gap", 4, 9, true, nil],
["facility_wall_top", 4, 9, true, nil],

["facility_wall", 4, 9, true, nil],
["facility_wall", 4, 9, true, nil],
["facility_wall", 4, 9, true, nil],
["facility_wall", 4, 9, true, nil],
["facility_ground2", 4, 9, false, nil],
["facility_ground1", 4, 9, false, nil],
["facility_wall", 4, 9, true, nil],
["facility_wall", 4, 9, true, nil],
["facility_wall", 4, 9, true, nil],

["cargo_roof_topr", 4, 9, true, nil],
["facility_ground1", 4, 9, false, nil],
["facility_ground2", 4, 9, false, nil],
["facility_ground3", 4, 9, false, nil],
["facility_ground4", 4, 9, false, nil],
["facility_ground1", 4, 9, false, nil],
["facility_ground2", 4, 9, false, nil],
["facility_ground3", 4, 9, false, nil],
["cargo_roof_topl", 4, 9, true, nil],

["cargo1_topr", 4, 9, true, nil],
["facility_ground1", 4, 9, false, nil],
["facility_ground3", 4, 9, false, nil],
["cargo_roof_topl", 4, 9, false, nil],
["cargo_roof_topc", 4, 9, false, nil],
["cargo_roof_topr", 4, 9, false, nil],
["facility_ground4", 4, 9, false, nil],
["facility_ground2", 4, 9, false, nil],
["cargo1_topl", 4, 9, true, nil],

["cargo2_botr", 4, 9, true, nil],
["facility_ground4", 4, 9, false, nil],
["facility_ground2", 4, 9, false, nil],
["cargo1_topl", 4, 9, false, nil],
["cargo_topc", 4, 9, false, nil],
["cargo1_topr", 4, 9, false, nil],
["facility_ground3", 4, 9, false, nil],
["facility_ground1", 4, 9, false, nil],
["cargo2_botl", 4, 9, true, nil],

["cargo_roof_topr", 4, 9, true, nil],
["facility_ground4", 4, 9, false, nil],
["facility_ground2", 4, 9, false, nil],
["cargo1_botl", 4, 9, false, nil],
["cargo1_botc", 4, 9, false, nil],
["cargo1_botr", 4, 9, false, nil],
["facility_ground3", 4, 9, false, nil],
["facility_ground1", 4, 9, false, nil],
["cargo_roof_topl", 4, 9, true, nil],

["cargo1_topr", 4, 9, true, nil],
["facility_ground3", 4, 9, false, nil],
["facility_ground2", 4, 9, false, nil],
["facility_ground3", 4, 9, false, nil],
["facility_ground4", 4, 9, false, nil],
["facility_ground1", 4, 9, false, nil],
["facility_ground4", 4, 9, false, nil],
["facility_ground3", 4, 9, false, nil],
["cargo1_topl", 4, 9, true, nil],

["cargo1_botr", 4, 9, true, nil],
["facility_ground3", 4, 9, false, nil],
["facility_ground2", 4, 9, false, nil],
["facility_ground3", 4, 9, false, nil],
["facility_ground4", 4, 9, false, nil],
["facility_ground1", 4, 9, false, nil],
["facility_ground4", 4, 9, false, nil],
["facility_ground3", 4, 9, false, nil],
["cargo1_botl", 4, 9, true, nil],

["blank", 4, 9, true, nil],
["blank", 4, 9, true, nil],
["blank", 4, 9, true, nil],
["blank", 4, 9, true, nil],
["blank", 4, 9, true, nil],
["blank", 4, 9, true, nil],
["blank", 4, 9, true, nil],
["blank", 4, 9, true, nil],
["blank", 4, 9, true, nil]

  ]
tile_list4.each do | tile_name, room_id, row_max, is_solid, transition_tile|
  Tile.create( tile_name: tile_name, room_id: room_id, row_max: row_max, is_solid: is_solid, transition_tile: transition_tile)
end
tile_list5 = [

["building_roof_topr", 5, 9, true, nil],
["facility_wall_gap", 5, 9, true, nil],
["facility_wall_top", 5, 9, true, nil],
["street_clean", 5, 9, false, nil],
["street_center_ns", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["facility_wall_top", 5, 9, true, nil],
["facility_wall_gap", 5, 9, true, nil],
["building_roof_topl", 5, 9, true, nil],

["building_roof_midr", 5, 9, true, nil],
["facility_wall", 5, 9, false, nil],
["facility_wall", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_center_ns", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["facility_wall", 5, 9, false, nil],
["facility_wall", 5, 9, false, nil],
["building_roof_midl", 5, 9, true, nil],

["building_roof_botr", 5, 9, true, nil],
["l_sidew1", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_center_ns", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["r_sidew1", 5, 9, false, nil],
["building_roof_botl", 5, 9, true, nil],

["building_topr", 5, 9, true, nil],
["l_sidew1", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_center_ns", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["r_sidew1", 5, 9, false, nil],
["building_topl", 5, 9, true, nil],

["building_midr", 5, 9, true, nil],
["l_sidew1", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_center_ns", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["r_sidew1", 5, 9, false, nil],
["building_midl", 5, 9, true, nil],

["building_roof_topr", 5, 9, true, nil],
["l_sidew1", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_center_ns", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["r_sidew1", 5, 9, false, nil],
["building_roof_topl", 5, 9, true, nil],

["building_roof_botr", 5, 9, true, nil],
["l_sidew1", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_center_ns", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["r_sidew1", 5, 9, false, nil],
["building_roof_botl", 5, 9, true, nil],

["building_topr", 5, 9, true, nil],
["l_sidew1", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_center_ns", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["r_sidew1", 5, 9, false, nil],
["building_topl", 5, 9, true, nil],

["building_midr", 5, 9, true, nil],
["l_sidew1", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_center_ns", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["street_clean", 5, 9, false, nil],
["r_sidew1", 5, 9, false, nil],
["building_midl", 5, 9, true, nil],

["blank", 5, 9, true, nil],
["blank", 5, 9, true, nil],
["blank", 5, 9, true, nil],
["blank", 5, 9, true, nil],
["blank", 5, 9, true, nil],
["blank", 5, 9, true, nil],
["blank", 5, 9, true, nil],
["blank", 5, 9, true, nil],
["blank", 5, 9, true, nil]

  ]
tile_list5.each do | tile_name, room_id, row_max, is_solid, transition_tile|
  Tile.create( tile_name: tile_name, room_id: room_id, row_max: row_max, is_solid: is_solid, transition_tile: transition_tile)
end

tile_list6 = [
["blank", 6, 8, true, nil],
["abdn_insidewall", 6, 8, true, nil],
["abdn_insidewall", 6, 8, true, nil],
["abdn_insidewall", 6, 8, true, nil],
["abdn_insidewall", 6, 8, true, nil],
["abdn_insidewall", 6, 8, true, nil],
["abdn_insidewall", 6, 8, true, nil],
["blank", 6, 8, true, nil],

["blank", 6, 8, true, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["blank", 6, 8, true, nil],

["blank", 6, 8, true, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["blank", 6, 8, true, nil],

["blank", 6, 8, true, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["blank", 6, 8, true, nil],

["abdn_outsidewall", 6, 8, true, nil],
["abdn_outsidewall", 6, 8, true, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_insideground", 6, 8, false, nil],
["abdn_outsidewall", 6, 8, true, nil],
["abdn_outsidewall", 6, 8, true, nil],
["abdn_outsidewall", 6, 8, true, nil],
["abdn_outsidewall", 6, 8, true, nil],

["blank", 6, 8, true, nil],
["blank", 6, 8, true, nil],
["blank", 6, 8, true, nil],
["blank", 6, 8, true, nil],
["blank", 6, 8, true, nil],
["blank", 6, 8, true, nil],
["blank", 6, 8, true, nil],
["blank", 6, 8, true, nil]

  ]
tile_list6.each do | tile_name, room_id, row_max, is_solid, transition_tile|
  Tile.create( tile_name: tile_name, room_id: room_id, row_max: row_max, is_solid: is_solid, transition_tile: transition_tile)
end

tile_list7 = [

["building_roof_topr", 7 ,12, true, nil],
["facility_ground2", 7 ,12, true, nil],
["collapsedroof_botl", 7 ,12, true, nil],
["building_roof_botc", 7 ,12, true, nil],
["collapsedroof_botr", 7 ,12, true, nil],
["collapsedroof_botl", 7 ,12, true, nil],
["building_roof_botc", 7 ,12, true, nil],
["building_roof_botc", 7 ,12, true, nil],
["collapsedroof_botr", 7 ,12, true, nil],
["building_botl", 7 ,12, true, nil],
["building_botr", 7 ,12, true, nil],
["blank", 7 ,12, true, nil],




["building_roof_midr", 7 ,12, true, nil],
["facility_ground1", 7 ,12, false, nil],
["collapsed_topl", 7 ,12, true, nil],
["building_topc", 7 ,12, true, nil],
["collapsed_topr", 7 ,12, true, nil],
["collapsed_topl", 7 ,12, true, nil],
["building_topc", 7 ,12, true, nil],
["building_topc", 7 ,12, true, nil],
["collapsed_topr", 7 ,12, true, nil],
["street_clean", 7 ,12,false, nil],
["street_center_we", 7 ,12, false, nil],
["blank", 7 ,12, true, nil],



["building_roof_botr", 7 ,12, true, nil],
["facility_ground2", 7 ,12, false, nil],
["collapsed_midl", 7 ,12, true, nil],
["building_midc", 7 ,12, true, nil],
["collapsed_midr", 7 ,12, true, nil],
["collapsed_midl", 7 ,12, true, nil],
["building_midc", 7 ,12, true, nil],
["building_midc", 7 ,12, true, nil],
["collapsed_midr", 7 ,12, true, nil],
["street_center_ns", 7, 12, false, nil],
["building_roof_topl", 7 ,12, true, nil],
["blank", 7 ,12, true, nil],


["building_topr", 7 ,12, true, nil],
["facility_ground2", 7 ,12, false, nil],
["collapsed_botl", 7 ,12, true, nil],
["building_botc", 7 ,12, true, nil],
["collapsed_botr", 7 ,12, true, nil],
["collapsed_botl", 7 ,12, true, nil],
["building_botc", 7 ,12, true, nil],
["building_botc", 7 ,12, true, nil],
["collapsed_botr", 7 ,12, true, nil],
["street_center_ns", 7, 12, false, nil],
["building_roof_midl", 7 ,12, true, nil],
["blank", 7 ,12, true, nil],



["building_midr", 7 ,12, true, nil],
["facility_ground2", 7 ,12, false, nil],
["facility_ground1", 7 ,12, false, nil],
["facility_ground2", 7 ,12, false, nil],
["facility_ground1", 7, 12, false, nil],
["facility_ground3", 7, 12, false, nil],
["facility_ground2", 7, 12, false, nil],
["facility_ground1", 7, 12, false, nil],
["facility_ground4", 7, 12, false, nil],
["street_center_ns", 7, 12, false, nil],
["building_roof_botl", 7 ,12, true, nil],
["blank", 7 ,12, true, nil],


["blank", 7 ,12, true, nil],
["abdn_insidewall", 7 ,12, true, nil],
["abdn_insidewall", 7 ,12, true, nil],
["blank", 7 ,12, true, nil],
["facility_ground1", 7, 12, false, nil],
["facility_ground3", 7, 12, false, nil],
["facility_ground2", 7, 12, false, nil],
["facility_ground1", 7, 12, false, nil],
["facility_ground4", 7, 12, false, nil],
["street_center_ns", 7, 12, false, nil],
["building_topl", 7 ,12, true, nil],
["blank", 7 ,12, true, nil],


["blank", 7 ,12, true, nil],
["abdn_insideground", 7 ,12, false, nil],
["abdn_insideground", 7 ,12, false, nil],
["blank", 7 ,12, true, nil],
["facility_ground1", 7, 12, false, nil],
["facility_ground3", 7, 12, false, nil],
["facility_ground2", 7, 12, false, nil],
["facility_ground1", 7, 12, false, nil],
["facility_ground4", 7, 12, false, nil],
["street_crater", 7, 12, false, nil],
["building_midl", 7 ,12, true, nil],
["blank", 7 ,12, true, nil],



["blank", 7 ,12, true, nil],
["abdn_insideground", 7 ,12, false, nil],
["abdn_insideground", 7 ,12, false, nil],
["rundown_botr", 7 ,12, true, nil],
["facility_ground3", 7, 12, false, nil],
["facility_ground1", 7, 12, false, nil],
["facility_ground3", 7, 12, false, nil],
["facility_ground2", 7, 12, false, nil],
["facility_ground1", 7, 12, false, nil],
["facility_ground4", 7, 12, false, nil],
["building_midl", 7 ,12, true, nil],
["blank", 7 ,12, true, nil],


["rundown_botl", 7 ,12, true, nil],
["abdn_insideground", 7 ,12, false, nil],
["abdn_insideground", 7 ,12, false, nil],
["abdn_insideground", 7 ,12, false, nil],
["facility_ground3", 7, 12, false, nil],
["facility_ground2", 7, 12, false, nil],
["facility_ground3", 7, 12, false, nil],
["facility_ground4", 7, 12, false, nil],
["facility_ground1", 7, 12, false, nil],
["facility_ground4", 7, 12, false, nil],
["building_midl", 7 ,12, true, nil],
["blank", 7 ,12, true, nil],

["building_roof_topl", 7 ,12, true, nil],
["building_roof_topc", 7 ,12, true, nil],
["building_roof_topr", 7 ,12, true, nil],
["building_roof_topl", 7 ,12, true, nil],
["building_roof_topc", 7 ,12, true, nil],
["building_roof_topr", 7 ,12, true, nil],
["building_roof_topl", 7 ,12, true, nil],
["building_roof_topc", 7 ,12, true, nil],
["building_roof_topc", 7 ,12, true, nil],
["building_roof_topr", 7 ,12, true, nil],
["building_midl", 7 ,12, true, nil],
["blank", 7 ,12, true, nil]



  ]
tile_list7.each do | tile_name, room_id, row_max, is_solid, transition_tile|
  Tile.create( tile_name: tile_name, room_id: room_id, row_max: row_max, is_solid: is_solid, transition_tile: transition_tile)
end

tile_list8 = [
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],

["blank", 8, 11, true, nil],
["building_roof_topl", 8, 11, true, nil],
["building_roof_topr", 8, 11, true, nil],
["l_sidew1", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["street_center_ns", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["r_sidew1", 8, 11, false, nil],
["building_roof_topl", 8, 11, true, nil],
["building_roof_topr", 8, 11, true, nil],
["blank", 8, 11, true, nil],


["blank", 8, 11, true, nil],
["building_roof_botl", 8, 11, true, nil],
["building_roof_botr", 8, 11, true, nil],
["l_sidew1", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["street_center_ns", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["r_sidew1", 8, 11, false, nil],
["building_roof_botl", 8, 11, true, nil],
["building_roof_botr", 8, 11, true, nil],
["blank", 8, 11, true, nil],

["blank", 8, 11, true, nil],
["building_topl", 8, 11, true, nil],
["building_topr", 8, 11, true, nil],
["l_sidew1", 8, 11, false, nil],
["street_crater", 8, 11, false, nil],
["street_center_ns", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["r_sidew1", 8, 11, false, nil],
["building_topl", 8, 11, true, nil],
["building_topr", 8, 11, true, nil],
["blank", 8, 11, true, nil],

["blank", 8, 11, true, nil],
["building_midl", 8, 11, true, nil],
["building_midr", 8, 11, true, nil],
["l_sidew1", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["street_center_ns", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["r_sidew1", 8, 11, false, nil],
["building_midl", 8, 11, true, nil],
["building_midr", 8, 11, true, nil],
["blank", 8, 11, true, nil],


["blank", 8, 11, true, nil],
["building_botl", 8, 11, true, nil],
["building_botr", 8, 11, true, nil],
["l_sidew1", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["street_center_ns", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["r_sidew1", 8, 11, false, nil],
["building_botl", 8, 11, true, nil],
["building_botr", 8, 11, true, nil],
["blank", 8, 11, true, nil],

["blank", 8, 11, true, nil],
["street_center_we", 8, 11, false, nil],
["street_center_we", 8, 11, false, nil],
["street_center_we", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["street_crater", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["street_center_we", 8, 11, false, nil],
["street_center_we", 8, 11, false, nil],
["street_center_we", 8, 11, false, nil],
["blank", 8, 11, true, nil],



["blank", 8, 11, true, nil],
["building_roof_topl", 8, 11, true, nil],
["collapsedroof_topr", 8, 11, true, nil],
["l_sidew1", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["street_center_ns", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["r_sidew1", 8, 11, false, nil],
["building_roof_topl", 8, 11, true, nil],
["building_roof_topr", 8, 11, true, nil],
["blank", 8, 11, true, nil],

["blank", 8, 11, true, nil],
["building_roof_midl", 8, 11, true, nil],
["collapsedroof_midr", 8, 11, true, nil],
["l_sidew1", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["street_center_ns", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["r_sidew1", 8, 11, false, nil],
["building_roof_topl", 8, 11, true, nil],
["building_roof_topr", 8, 11, true, nil],
["blank", 8, 11, true, nil],


["blank", 8, 11, true, nil],
["building_roof_botl", 8, 11, true, nil],
["collapsedroof_botr", 8, 11, true, nil],
["l_sidew1", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["street_center_ns", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["r_sidew1", 8, 11, false, nil],
["building_roof_botl", 8, 11, true, nil],
["building_roof_botr", 8, 11, true, nil],
["blank", 8, 11, true, nil],

["blank", 8, 11, true, nil],
["building_topl", 8, 11, true, nil],
["collapsed_topr", 8, 11, true, nil],
["l_sidew1", 8, 11, false, nil],
["street_crater", 8, 11, false, nil],
["street_center_ns", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["r_sidew1", 8, 11, false, nil],
["building_topl", 8, 11, true, nil],
["building_topr", 8, 11, true, nil],
["blank", 8, 11, true, nil],

["blank", 8, 11, true, nil],
["building_midl", 8, 11, true, nil],
["collapsedroof_midr", 8, 11, true, nil],
["l_sidew1", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["street_center_ns", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["r_sidew1", 8, 11, false, nil],
["building_midl", 8, 11, true, nil],
["building_midr", 8, 11, true, nil],
["blank", 8, 11, true, nil],


["blank", 8, 11, true, nil],
["building_botl", 8, 11, true, nil],
["collapsed_botr", 8, 11, true, nil],
["l_sidew1", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["street_center_ns", 8, 11, false, nil],
["street_clean", 8, 11, false, nil],
["r_sidew1", 8, 11, false, nil],
["building_botl", 8, 11, true, nil],
["building_botr", 8, 11, true, nil],
["blank", 8, 11, true, nil],

["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil],
["blank", 8, 11, true, nil]

  ]
tile_list8.each do | tile_name, room_id, row_max, is_solid, transition_tile|
  Tile.create( tile_name: tile_name, room_id: room_id, row_max: row_max, is_solid: is_solid, transition_tile: transition_tile)
end

tile_list9 = [
["blank", 9, 8, true, nil],
["building_roof_topr", 9, 8, true, nil],
["building_botc", 9, 8, true, nil],
["building_roof_botl", 9, 8, true, nil],
["building_roof_botc", 9, 8, true, nil],
["building_roof_botc", 9, 8, true, nil],
["building_roof_botr", 9, 8, true, nil],
["building_roof_topl", 9, 8, true, nil],

["blank", 9, 8, true, nil],
["building_roof_botr", 9, 8, true, nil],
["facility_ground4", 9, 8, true, nil],
["rundown_botl", 9, 8, true, nil],
["rundown_openl", 9, 8, false, nil],
["rundown_openr", 9, 8, false, nil],
["rundown_botr", 9, 8, true, nil],
["building_roof_midl", 9, 8, true, nil],


["blank", 9, 8, true, nil],
["building_topl", 9, 8, true, nil],
["facility_ground1", 9, 8, false, nil],
["facility_ground4", 9, 8, false, nil],
["facility_ground3", 9, 8, false, nil],
["facility_ground1", 9, 8, false, nil],
["facility_ground2", 9, 8, false, nil],
["building_roof_botl", 9, 8, true, nil],


["blank", 9, 8, true, nil],
["building_midl", 9, 8, true, nil],
["facility_ground1", 9, 8, false, nil],
["facility_ground4", 9, 8, false, nil],
["facility_ground3", 9, 8, false, nil],
["facility_ground1", 9, 8, false, nil],
["facility_ground2", 9, 8, false, nil],
["building_topl", 9, 8, true, nil],

["blank", 9, 8, true, nil],
["building_botl", 9, 8, true, nil],
["facility_ground1", 9, 8, false, nil],
["facility_ground4", 9, 8, false, nil],
["facility_ground3", 9, 8, false, nil],
["facility_ground1", 9, 8, false, nil],
["facility_ground2", 9, 8, false, nil],
["building_midl", 9, 8, true, nil],


["blank", 9, 8, true, nil],
["street_center_we", 9, 8, false, nil],
["facility_ground1", 9, 8, false, nil],
["facility_ground4", 9, 8, false, nil],
["facility_ground3", 9, 8, false, nil],
["facility_ground1", 9, 8, false, nil],
["facility_ground2", 9, 8, false, nil],
["building_botl", 9, 8, true, nil],

["blank", 9, 8, true, nil],
["building_roof_topr", 9, 8, true, nil],
["facility_ground4", 9, 8, false, nil],
["facility_ground3", 9, 8, false, nil],
["facility_ground2", 9, 8, false, nil],
["facility_ground2", 9, 8, false, nil],
["facility_ground1", 9, 8, false, nil],
["building_roof_topl", 9, 8, true, nil],

["blank", 9, 8, true, nil],
["building_roof_botr", 9, 8, true, nil],
["facility_ground2", 9, 8, false, nil],
["facility_ground1", 9, 8, false, nil],
["facility_ground2", 9, 8, false, nil],
["facility_ground3", 9, 8, false, nil],
["facility_ground4", 9, 8, false, nil],
["building_roof_botl", 9, 8, true, nil],


["blank", 9, 8, true, nil],
["building_topr", 9, 8, true, nil],
["building_roof_topl", 9, 8, true, nil],
["building_roof_topc", 9, 8, true, nil],
["building_roof_topc", 9, 8, true, nil],
["building_roof_topc", 9, 8, true, nil],
["building_roof_topr", 9, 8, true, nil],
["building_topl", 9, 8, true, nil],


  ]
tile_list9.each do | tile_name, room_id, row_max, is_solid, transition_tile|
  Tile.create( tile_name: tile_name, room_id: room_id, row_max: row_max, is_solid: is_solid, transition_tile: transition_tile)
end
